### ISSUE TITLE
Tetrimino vs. Tetromino

### ISSUE THREAD

**Issue by tfoliva** [ModernCppSG/tetris#5]
Apparently the "correct" name for the mathematical object (a figure composed of four squares) is *tetromino*, however in Tetris vocabulary they are called *tetrimino* in a sort of wordplay.

Another possibility still is *polymino* which is the 'parent class' of tetromino; that is, a tetromino *is a* polymino. A domino is also a polymino, for that matter. So to call the tetrominoes/tetriminos polyminos is technically correct I guess. By the way: the plural for tetromino is tetrominoes but the plural for tetrimino is tetriminos.

Which naming convention should we go for? Tetrimino, Tetromino or Polymino? For the time being I named evertything tetrimino, but if you guys prefer we could still change the naming convention.

source: https://en.wikipedia.org/wiki/Tetromino

**Comment by LeoBelmont** [comment]
I also named everything tetrimino so I suggest we just stick with that one lol.

**Comment by tfoliva** [comment]
Yeah. Even though 'tetrimino' is technically incorrect, I believe it makes sense given the context. It's sort of a 'commercial' name in the Tetris scenario. I mean, it's a naming convention started by Nintendo I believe. Considering that the project deals with Tetris, it would make more sense to stick with the game naming convention than with the geometric one.

**Comment by tfoliva** [comment]
Please consider **Tetrimino**/**Tetriminos** as the standard nomenclature from now on.
